import { GoogleGenAI } from "@google/genai";

// This service is prepared for future enhancements where the "page description" 
// could be dynamically generated by Gemini based on the URL.

const getAIClient = () => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const summarizeUrl = async (url: string): Promise<string> => {
    try {
        const ai = getAIClient();
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Summarize what this website is about in one catchy sentence: ${url}`,
        });
        return response.text || "No description available.";
    } catch (error) {
        console.error("Failed to fetch summary", error);
        return "Could not load summary.";
    }
};